# -*- coding: utf-8 -*-
"""27.05.colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Og1nZDpgkG8Cz8mjW5wlSOJT-70qJ_p
"""

x =5
y = "Привет мир"
x =10
z = 1.5
arr =[1,2,3,4,5,0.9,"test1"]

arr2 = arr

print(type(arr))
print(arr)
print(arr[6],arr[2])

print(len(arr))
print (arr2)

try:
  x=int(input("Введи делимое: "))
  y=int(input("Введи делитель: "))
  a= x/y
  print(a)
except ZeroDivisionError:
  print("деление на 0")
  x=int(input("Введи делимое: "))
  y=int(input("Введи делитель: "))
  a= x/y
  print(a)
finally:
  print("Блок файнали отработал")

import random
a = random.randint(40,90)
print(a)

import random
x=[1,8,9,60,43,73,7, "p","yj"]
print("случайное число из списка:", random.choice(x))

import random
arr =[1,4,6,7,0,15,34,"jghh","kkll","kghj"] #Создал переменную со значениями
b = random.choice(arr)
print(b)

import random

x = random.random()
print(x)

import random
c= random.uniform(0.7,9.8)
print(c)

import random
brocok1=random.randint(1,6)
brocok2=random.randint(1,6)
brocok3=random.randint(1,6)
brocok4=random.randint(1,6)

total = brocok1 + brocok2 + brocok3 + brocok4

print("Бросок 1:",brocok1, "Бросок 2:",brocok2, "Бросок 3:",brocok3, "Бросок 4:",brocok4)
print("Всего очков:", total)

import random

x=4
y=[]
total=0

while x !=0:
  brocok =random.randint(1,6)
  x -=1
  y.append(brocok)
  print(y)

total = sum(y)
print("очков", total)

import random

x=4
y=[]
total=0

while x !=0:
  brocok =random.randint(1,6)
  x -=1
  y.append(brocok)
  print(y)

for i in y:
  
  total +=i
  print(total)


print("всего очков:", total)

import random 

chars ="+-/*!&$#?=@<>abcdefghijklnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
lenght = input("длина пароля:")

password =""

try:
  lenght = int(lenght)
  for i in range(lenght):
    password += random.choice(chars)
  print(password)
except ValueError:
  print("Вы ввели буквы вместо цифр")
  lenght = input("длина пароля:")
  lenght = int(lenght)
  for i in range(lenght):
    password += random.choice(chars)
  print(password)

x=5.78
y= int(x)
print(y)