# -*- coding: utf-8 -*-
"""27.05.colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Og1nZDpgkG8Cz8mjW5wlSOJT-70qJ_p
"""

print("Привет мир")